# Makefile for NQueens
#######################################################
# Name:熊伟伦  ID:5120379076

PROGRAM = NQueens
SOURCE = NQueens.cpp

#######################################################

all:
	g++ $(SOURCE) -o $(PROGRAM)

#######################################################

clean:
	rm $(PROGRAM)
